import type { Metadata } from "next";
import "./globals.css";
import React from "react";
import {Header} from "@/components/header/Header";
import {Footer} from "@/components/footer/Footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
    <body className={"jost-400"}>
    <Header/>
    {children}
    <Footer/>
    </body>
    </html>
  );
}
